# Data Cleaning and Feature Engineering

The dataset used is the historical solar radiation time series of Solcast from Manila, Philippines.

In [8]:
# import libraries
import numpy as np
import pandas as pd

In [9]:
# read the dataframe
df = pd.read_csv('..\dataset\Solcast_leon_20_21.csv')

In [10]:
# printout the column names
df.columns

Index(['PeriodEnd', 'PeriodStart', 'Period', 'AirTemp', 'Azimuth',
       'CloudOpacity', 'DewpointTemp', 'Dhi', 'Dni', 'Ebh', 'Ghi',
       'GtiFixedTilt', 'GtiTracking', 'PrecipitableWater', 'RelativeHumidity',
       'SnowWater', 'SurfacePressure', 'WindDirection10m', 'WindSpeed10m',
       'Zenith', 'AlbedoDaily'],
      dtype='object')

In [11]:
# select some features
df= df[['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi',
       'PrecipitableWater', 'RelativeHumidity', 'SurfacePressure',
       'WindDirection10m', 'WindSpeed10m']]

In [12]:
# randomly display 10 rows
df.sample(10)

,PeriodEnd,PeriodStart,AirTemp,Dhi,Dni,Ghi,PrecipitableWater,RelativeHumidity,SurfacePressure,WindDirection10m,WindSpeed10m
11780,2021-05-04T22:00:00Z,2021-05-04T21:00:00Z,9.4,0,0,0,12.3,71.3,915.3,348,3.4
6315,2020-09-19T05:00:00Z,2020-09-19T04:00:00Z,12.0,0,0,0,23.9,87.3,909.8,59,3.1
3871,2020-06-09T09:00:00Z,2020-06-09T08:00:00Z,10.9,233,483,543,9.7,62.4,918.4,346,1.1
6993,2020-10-17T11:00:00Z,2020-10-17T10:00:00Z,10.3,182,564,494,13.9,48.5,915.3,145,1.2
8886,2021-01-04T08:00:00Z,2021-01-04T07:00:00Z,-3.5,0,2,1,5.4,85.5,907.3,294,4.0
5706,2020-08-24T20:00:00Z,2020-08-24T19:00:00Z,21.2,1,0,1,19.1,42.7,915.6,159,2.5
26,2020-01-01T04:00:00Z,2020-01-01T03:00:00Z,1.6,0,0,0,3.8,71.6,927.5,10,0.7
7879,2020-11-23T09:00:00Z,2020-11-23T08:00:00Z,6.2,35,561,131,10.7,69.6,925.0,42,1.3
11743,2021-05-03T09:00:00Z,2021-05-03T08:00:00Z,8.1,109,792,555,8.2,64.1,918.4,79,1.2
6236,2020-09-15T22:00:00Z,2020-09-15T21:00:00Z,17.0,0,0,0,16.3,47.7,919.5,279,0.8

In [13]:
old_names= ['PeriodEnd', 'PeriodStart', 'AirTemp', 'Dhi', 'Dni', 'Ghi','PrecipitableWater', 'RelativeHumidity',
             'SurfacePressure', 'WindDirection10m', 'WindSpeed10m'] 
new_names= ['PeriodEnd','PeriodStart','Temperature', 'Radiation', 'DNI', 'GHI', 'Precipitation', 'Humidity', 
             'Pressure', 'WindDirection', 'WindSpeed']
df.rename(columns= dict(zip(old_names, new_names)), inplace=True)

In [14]:
# display dataframe
df.head()

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-12-31T02:00:00Z,2019-12-31T01:00:00Z,3.8,0,0,0,3.9,47.0,928.1,355,1.1
1,2019-12-31T03:00:00Z,2019-12-31T02:00:00Z,3.7,0,0,0,3.9,44.9,927.7,354,1.1
2,2019-12-31T04:00:00Z,2019-12-31T03:00:00Z,3.6,0,0,0,4.0,42.6,927.5,358,1.1
3,2019-12-31T05:00:00Z,2019-12-31T04:00:00Z,3.4,0,0,0,4.3,40.7,927.4,8,0.9
4,2019-12-31T06:00:00Z,2019-12-31T05:00:00Z,3.1,0,0,0,4.4,39.8,927.7,28,0.5

In [15]:
# show a summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17445 entries, 0 to 17444
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17445 non-null  object
 1   PeriodStart    17445 non-null  object
 2   Temperature    17445 non-null  float64
 3   Radiation      17445 non-null  int64
 4   DNI            17445 non-null  int64
 5   GHI            17445 non-null  int64
 6   Precipitation  17445 non-null  float64
 7   Humidity       17445 non-null  float64
 8   Pressure       17445 non-null  float64
 9   WindDirection  17445 non-null  int64
 10  WindSpeed      17445 non-null  float64
dtypes: float64(5), int64(4), object(2)
memory usage: 1.5+ MB

In [16]:
 # interpret columns as appropriate data types to ensure compatibility
df['Radiation']     = df['Radiation'].astype(float)
df['Temperature']   = df['Temperature'].astype(float) # or int
df['Pressure']      = df['Pressure'].astype(float)
df['Humidity']      = df['Humidity'].astype(int) # or int
df['WindDirection'] = df['WindDirection'].astype(float)
df['WindSpeed']     = df['WindSpeed'].astype(float)
df['PeriodStart'] = pd.to_datetime(df['PeriodStart']).dt.to_period('T').dt.to_timestamp()
df['PeriodEnd'] = pd.to_datetime(df['PeriodEnd']).dt.to_period('T').dt.to_timestamp()

C:\ProgramData\Anaconda3\envs\mlops\lib\site-packages\pandas\core\arrays\datetimes.py:1143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

In [17]:
# display dataframe summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17445 entries, 0 to 17444
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17445 non-null  datetime64[ns]
 1   PeriodStart    17445 non-null  datetime64[ns]
 2   Temperature    17445 non-null  float64
 3   Radiation      17445 non-null  float64
 4   DNI            17445 non-null  int64
 5   GHI            17445 non-null  int64
 6   Precipitation  17445 non-null  float64
 7   Humidity       17445 non-null  int32
 8   Pressure       17445 non-null  float64
 9   WindDirection  17445 non-null  float64
 10  WindSpeed      17445 non-null  float64
dtypes: datetime64[ns](2), float64(6), int32(1), int64(2)
memory usage: 1.4 MB

In [18]:
# display top 6 rows
df.head(6)

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed
0,2019-12-31 02:00:00,2019-12-31 01:00:00,3.8,0.0,0,0,3.9,47,928.1,355.0,1.1
1,2019-12-31 03:00:00,2019-12-31 02:00:00,3.7,0.0,0,0,3.9,44,927.7,354.0,1.1
2,2019-12-31 04:00:00,2019-12-31 03:00:00,3.6,0.0,0,0,4.0,42,927.5,358.0,1.1
3,2019-12-31 05:00:00,2019-12-31 04:00:00,3.4,0.0,0,0,4.3,40,927.4,8.0,0.9
4,2019-12-31 06:00:00,2019-12-31 05:00:00,3.1,0.0,0,0,4.4,39,927.7,28.0,0.5
5,2019-12-31 07:00:00,2019-12-31 06:00:00,2.8,0.0,0,0,4.5,40,928.0,41.0,0.4

In [19]:
# create new features(year, month, day) from start and end time of data collection  
df['YearPS'] = pd.to_datetime(df['PeriodStart']).dt.year
df['YearPE'] = pd.to_datetime(df['PeriodEnd']).dt.year

df['MonthPS'] = pd.to_datetime(df['PeriodStart']).dt.month
df['MonthPE'] = pd.to_datetime(df['PeriodEnd']).dt.month

df['HourPS'] = pd.to_datetime(df['PeriodStart']).dt.hour
df['HourPE'] = pd.to_datetime(df['PeriodEnd']).dt.hour

In [20]:
df.head(5)

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE
0,2019-12-31 02:00:00,2019-12-31 01:00:00,3.8,0.0,0,0,3.9,47,928.1,355.0,1.1,2019,2019,12,12,1,2
1,2019-12-31 03:00:00,2019-12-31 02:00:00,3.7,0.0,0,0,3.9,44,927.7,354.0,1.1,2019,2019,12,12,2,3
2,2019-12-31 04:00:00,2019-12-31 03:00:00,3.6,0.0,0,0,4.0,42,927.5,358.0,1.1,2019,2019,12,12,3,4
3,2019-12-31 05:00:00,2019-12-31 04:00:00,3.4,0.0,0,0,4.3,40,927.4,8.0,0.9,2019,2019,12,12,4,5
4,2019-12-31 06:00:00,2019-12-31 05:00:00,3.1,0.0,0,0,4.4,39,927.7,28.0,0.5,2019,2019,12,12,5,6

In [21]:
# create a new feature for sunrise using the function below; fill time for sunrise
def time_to_sunrise(row):
    """
    A function for identifying time of sunrise.
    """
    value= 0
    if row['HourPS']== 4 and row['HourPE']== 5 and row['Radiation']> 0:
        value= '05:00:00'
    elif row['HourPS']== 5 and row['HourPE']== 6 and row['Radiation']> 0:
        value= '06:00:00'
    return value

In [22]:
# create a new column using the function above
df['Sunrise']= df.apply(time_to_sunrise, axis=1)
df.head(5)

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise
0,2019-12-31 02:00:00,2019-12-31 01:00:00,3.8,0.0,0,0,3.9,47,928.1,355.0,1.1,2019,2019,12,12,1,2,0
1,2019-12-31 03:00:00,2019-12-31 02:00:00,3.7,0.0,0,0,3.9,44,927.7,354.0,1.1,2019,2019,12,12,2,3,0
2,2019-12-31 04:00:00,2019-12-31 03:00:00,3.6,0.0,0,0,4.0,42,927.5,358.0,1.1,2019,2019,12,12,3,4,0
3,2019-12-31 05:00:00,2019-12-31 04:00:00,3.4,0.0,0,0,4.3,40,927.4,8.0,0.9,2019,2019,12,12,4,5,0
4,2019-12-31 06:00:00,2019-12-31 05:00:00,3.1,0.0,0,0,4.4,39,927.7,28.0,0.5,2019,2019,12,12,5,6,0

In [23]:
# create a new feature for sunset using the function below; fill time for sunset
def time_to_sunset(row):
    """
    A function for identifying time of sunset.
    """
    value= 0
    if row['HourPS'] == 17 and row['HourPE'] == 18 and row['Radiation']> 0:
        value= '18:00:00'
    elif row['HourPS'] == 18 and row['HourPE']== 19 and row['Radiation']> 0:
        value= '19:00:00'
    return value

In [24]:
df.Sunrise.unique()

array([0, '06:00:00', '05:00:00'], dtype=object)

In [25]:
# create a new column using the function above
df['Sunset']= df.apply(time_to_sunset, axis=1)
df.tail(5)

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset
17440,2021-12-26 18:00:00,2021-12-26 17:00:00,7.0,0.0,0,0,19.6,98,906.2,177.0,3.1,2021,2021,12,12,17,18,0,0
17441,2021-12-26 19:00:00,2021-12-26 18:00:00,7.3,0.0,0,0,18.1,98,906.2,190.0,2.5,2021,2021,12,12,18,19,0,0
17442,2021-12-26 20:00:00,2021-12-26 19:00:00,7.6,0.0,0,0,17.3,98,906.1,196.0,2.5,2021,2021,12,12,19,20,0,0
17443,2021-12-26 21:00:00,2021-12-26 20:00:00,8.1,0.0,0,0,17.9,96,905.7,204.0,3.3,2021,2021,12,12,20,21,0,0
17444,2021-12-26 22:00:00,2021-12-26 21:00:00,8.8,0.0,0,0,18.7,95,905.3,211.0,5.1,2021,2021,12,12,21,22,0,0

In [26]:
df.Sunset.unique()

array([0, '18:00:00', '19:00:00'], dtype=object)

In [27]:
# show summary of our dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17445 entries, 0 to 17444
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      17445 non-null  datetime64[ns]
 1   PeriodStart    17445 non-null  datetime64[ns]
 2   Temperature    17445 non-null  float64
 3   Radiation      17445 non-null  float64
 4   DNI            17445 non-null  int64
 5   GHI            17445 non-null  int64
 6   Precipitation  17445 non-null  float64
 7   Humidity       17445 non-null  int32
 8   Pressure       17445 non-null  float64
 9   WindDirection  17445 non-null  float64
 10  WindSpeed      17445 non-null  float64
 11  YearPS         17445 non-null  int64
 12  YearPE         17445 non-null  int64
 13  MonthPS        17445 non-null  int64
 14  MonthPE        17445 non-null  int64
 15  HourPS         17445 non-null  int64
 16  HourPE         17445 non-null  int64
 17  Sunrise        17445 non-null  object
 18  Sunset         17445 non-null  object
dtypes: datetime64[ns](2), float64(6), int32(1), int64(8), object(2)
memory usage: 2.5+ MB

In [28]:
# changing integer values to datetime format
df_new = df.loc[~((df['Radiation'] == 0) & (df['DNI'] == 0) & (df['GHI'] == 0)),:]

In [29]:
# show summary of our dataframe
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9351 entries, 6 to 17439
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9351 non-null   datetime64[ns]
 1   PeriodStart    9351 non-null   datetime64[ns]
 2   Temperature    9351 non-null   float64
 3   Radiation      9351 non-null   float64
 4   DNI            9351 non-null   int64
 5   GHI            9351 non-null   int64
 6   Precipitation  9351 non-null   float64
 7   Humidity       9351 non-null   int32
 8   Pressure       9351 non-null   float64
 9   WindDirection  9351 non-null   float64
 10  WindSpeed      9351 non-null   float64
 11  YearPS         9351 non-null   int64
 12  YearPE         9351 non-null   int64
 13  MonthPS        9351 non-null   int64
 14  MonthPE        9351 non-null   int64
 15  HourPS         9351 non-null   int64
 16  HourPE         9351 non-null   int64
 17  Sunrise        9351 non-null   object
 18  Sunset         9351 non-null   object
dtypes: datetime64[ns](2), float64(6), int32(1), int64(8), object(2)
memory usage: 1.4+ MB

In [30]:
# display 10 random samples of the dataframe
df_new.sample(10)

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset
3393,2020-05-20 11:00:00,2020-05-20 10:00:00,22.7,85.0,955,892,10.0,39,918.1,211.0,0.8,2020,2020,5,5,10,11,0,0
17171,2021-12-15 13:00:00,2021-12-15 12:00:00,13.4,36.0,922,411,6.4,25,923.4,56.0,1.0,2021,2021,12,12,12,13,0,0
15368,2021-10-01 10:00:00,2021-10-01 09:00:00,16.6,251.0,13,259,18.7,45,920.0,249.0,1.6,2021,2021,10,10,9,10,0,0
7019,2020-10-18 13:00:00,2020-10-18 12:00:00,15.8,91.0,861,614,12.5,47,919.2,171.0,2.0,2020,2020,10,10,12,13,0,0
925,2020-02-07 15:00:00,2020-02-07 14:00:00,10.1,101.0,739,425,10.0,69,918.6,197.0,2.0,2020,2020,2,2,14,15,0,0
12346,2021-05-28 12:00:00,2021-05-28 11:00:00,16.6,427.0,0,427,25.7,68,917.4,84.0,1.8,2021,2021,5,5,11,12,0,0
15038,2021-09-17 16:00:00,2021-09-17 15:00:00,23.5,114.0,658,462,20.2,33,912.7,264.0,4.7,2021,2021,9,9,15,16,0,0
3472,2020-05-23 18:00:00,2020-05-23 17:00:00,18.7,87.0,604,324,17.9,65,925.7,68.0,3.3,2020,2020,5,5,17,18,0,18:00:00
12654,2021-06-10 08:00:00,2021-06-10 07:00:00,17.6,90.0,712,423,18.1,58,919.9,47.0,1.3,2021,2021,6,6,7,8,0,0
10641,2021-03-18 11:00:00,2021-03-18 10:00:00,7.5,327.0,53,360,6.6,51,920.5,23.0,5.2,2021,2021,3,3,10,11,0,0

In [31]:
# convert datetime column of endperiod to just date
df_new['Date']= pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

C:\Users\Usuario\AppData\Local\Temp/ipykernel_17396/3941231241.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Date']= pd.to_datetime(df_new['PeriodEnd']).dt.normalize()

In [32]:
# convert the column (it's a string) to datetime type
dt_series= pd.to_datetime(df_new['Date'])

# create datetime index passing the datetime series
dt_index= pd.DatetimeIndex(dt_series.values)

# set new index
df_new1= df_new.set_index(dt_index)

In [33]:
# display first 5 rows
df_new1.head()

,PeriodEnd,PeriodStart,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,YearPS,YearPE,MonthPS,MonthPE,HourPS,HourPE,Sunrise,Sunset,Date
2019-12-31,2019-12-31 08:00:00,2019-12-31 07:00:00,2.6,0.0,3,1,4.6,41,928.0,18.0,0.6,2019,2019,12,12,7,8,0,0,2019-12-31
2019-12-31,2019-12-31 09:00:00,2019-12-31 08:00:00,3.5,36.0,182,57,4.3,42,928.2,24.0,0.8,2019,2019,12,12,8,9,0,0,2019-12-31
2019-12-31,2019-12-31 10:00:00,2019-12-31 09:00:00,6.2,43.0,706,205,4.0,39,928.5,41.0,0.8,2019,2019,12,12,9,10,0,0,2019-12-31
2019-12-31,2019-12-31 11:00:00,2019-12-31 10:00:00,8.5,47.0,856,327,3.9,34,928.8,58.0,0.5,2019,2019,12,12,10,11,0,0,2019-12-31
2019-12-31,2019-12-31 12:00:00,2019-12-31 11:00:00,9.6,51.0,906,404,3.7,32,929.0,152.0,0.4,2019,2019,12,12,11,12,0,0,2019-12-31

In [34]:
# display a summary of our dataframe
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9351 entries, 2019-12-31 to 2021-12-26
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PeriodEnd      9351 non-null   datetime64[ns]
 1   PeriodStart    9351 non-null   datetime64[ns]
 2   Temperature    9351 non-null   float64
 3   Radiation      9351 non-null   float64
 4   DNI            9351 non-null   int64
 5   GHI            9351 non-null   int64
 6   Precipitation  9351 non-null   float64
 7   Humidity       9351 non-null   int32
 8   Pressure       9351 non-null   float64
 9   WindDirection  9351 non-null   float64
 10  WindSpeed      9351 non-null   float64
 11  YearPS         9351 non-null   int64
 12  YearPE         9351 non-null   int64
 13  MonthPS        9351 non-null   int64
 14  MonthPE        9351 non-null   int64
 15  HourPS         9351 non-null   int64
 16  HourPE         9351 non-null   int64
 17  Sunrise        9351 non-null   object
 18  Sunset         9351 non-null   object
 19  Date           9351 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(6), int32(1), int64(8), object(2)
memory usage: 1.5+ MB

In [35]:
# sample daily average for the solar and weather features
df_new1['Daily_radiation']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Radiation'].mean()
df_new1['Daily_DNI']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['DNI'].mean()
df_new1['Daily_GHI']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['GHI'].mean()
df_new1['Daily_Temp']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Temperature'].mean()
df_new1['Daily_Precip']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Precipitation'].mean()
df_new1['Daily_Humidity']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Humidity'].mean()
df_new1['Daily_Pressure']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['Pressure'].mean()
df_new1['Daily_WindDir']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindDirection'].mean()
df_new1['Daily_WindSpeed']= df_new1.reset_index().groupby(pd.Grouper(key='Date', freq='1D'))['WindSpeed'].mean()

In [36]:
# display a summary of our dataframe
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9351 entries, 2019-12-31 to 2021-12-26
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9351 non-null   datetime64[ns]
 1   PeriodStart      9351 non-null   datetime64[ns]
 2   Temperature      9351 non-null   float64
 3   Radiation        9351 non-null   float64
 4   DNI              9351 non-null   int64
 5   GHI              9351 non-null   int64
 6   Precipitation    9351 non-null   float64
 7   Humidity         9351 non-null   int32
 8   Pressure         9351 non-null   float64
 9   WindDirection    9351 non-null   float64
 10  WindSpeed        9351 non-null   float64
 11  YearPS           9351 non-null   int64
 12  YearPE           9351 non-null   int64
 13  MonthPS          9351 non-null   int64
 14  MonthPE          9351 non-null   int64
 15  HourPS           9351 non-null   int64
 16  HourPE           9351 non-null   int64
 17  Sunrise          9351 non-null   object
 18  Sunset           9351 non-null   object
 19  Date             9351 non-null   datetime64[ns]
 20  Daily_radiation  9351 non-null   float64
 21  Daily_DNI        9351 non-null   float64
 22  Daily_GHI        9351 non-null   float64
 23  Daily_Temp       9351 non-null   float64
 24  Daily_Precip     9351 non-null   float64
 25  Daily_Humidity   9351 non-null   float64
 26  Daily_Pressure   9351 non-null   float64
 27  Daily_WindDir    9351 non-null   float64
 28  Daily_WindSpeed  9351 non-null   float64
dtypes: datetime64[ns](3), float64(15), int32(1), int64(8), object(2)
memory usage: 2.1+ MB

In [37]:
# drop irrelevant features
new_df= df_new1.drop(['PeriodStart', 'YearPS', 'HourPS', 'HourPE', 'Sunrise', 'Sunset', 'MonthPS', 'YearPE'], axis= 1)

In [38]:
# display first 10 rows
new_df.head(10)

,PeriodEnd,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_GHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-12-31,2019-12-31 08:00:00,2.6,0.0,3,1,4.6,41,928.0,18.0,0.6,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 09:00:00,3.5,36.0,182,57,4.3,42,928.2,24.0,0.8,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 10:00:00,6.2,43.0,706,205,4.0,39,928.5,41.0,0.8,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 11:00:00,8.5,47.0,856,327,3.9,34,928.8,58.0,0.5,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 12:00:00,9.6,51.0,906,404,3.7,32,929.0,152.0,0.4,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 13:00:00,10.3,52.0,920,427,3.5,33,928.6,170.0,0.9,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 14:00:00,10.6,50.0,902,394,3.5,34,927.7,176.0,1.0,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 15:00:00,10.5,46.0,845,308,3.6,38,927.1,202.0,0.8,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 16:00:00,9.1,37.0,714,181,3.8,47,927.1,211.0,0.7,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2019-12-31,2019-12-31 17:00:00,6.2,15.0,283,44,3.9,55,927.2,212.0,0.6,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71

In [39]:
# show a summary of the dataframe
new_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9351 entries, 2019-12-31 to 2021-12-26
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PeriodEnd        9351 non-null   datetime64[ns]
 1   Temperature      9351 non-null   float64
 2   Radiation        9351 non-null   float64
 3   DNI              9351 non-null   int64
 4   GHI              9351 non-null   int64
 5   Precipitation    9351 non-null   float64
 6   Humidity         9351 non-null   int32
 7   Pressure         9351 non-null   float64
 8   WindDirection    9351 non-null   float64
 9   WindSpeed        9351 non-null   float64
 10  MonthPE          9351 non-null   int64
 11  Date             9351 non-null   datetime64[ns]
 12  Daily_radiation  9351 non-null   float64
 13  Daily_DNI        9351 non-null   float64
 14  Daily_GHI        9351 non-null   float64
 15  Daily_Temp       9351 non-null   float64
 16  Daily_Precip     9351 non-null   float64
 17  Daily_Humidity   9351 non-null   float64
 18  Daily_Pressure   9351 non-null   float64
 19  Daily_WindDir    9351 non-null   float64
 20  Daily_WindSpeed  9351 non-null   float64
dtypes: datetime64[ns](2), float64(15), int32(1), int64(3)
memory usage: 1.5 MB

In [40]:
# dropping ALL duplicate values except the last value
new_df= new_df[~new_df.Date.duplicated(keep='last')]

In [41]:
# show the number of rows and columns available
new_df.shape

(727, 21)

In [42]:
# print the first 10 rows
new_df.head(10)

,PeriodEnd,Temperature,Radiation,DNI,GHI,Precipitation,Humidity,Pressure,WindDirection,WindSpeed,...,Date,Daily_radiation,Daily_DNI,Daily_GHI,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed
2019-12-31,2019-12-31 17:00:00,6.2,15.0,283,44,3.9,55,927.2,212.0,0.6,...,2019-12-31,37.7,631.7,234.8,7.71,3.88,39.5,928.02,126.4,0.71
2020-01-01,2020-01-01 17:00:00,5.0,18.0,236,43,5.5,67,926.8,217.0,1.0,...,2020-01-01,40.8,626.8,234.5,6.05,4.19,57.5,927.81,155.9,0.65
2020-01-02,2020-01-02 17:00:00,4.1,24.0,151,39,6.6,72,925.1,139.0,0.5,...,2020-01-02,101.5,309.3,191.5,5.01,6.66,63.7,925.93,133.0,0.89
2020-01-03,2020-01-03 17:00:00,5.0,28.0,87,36,9.6,79,928.6,103.0,0.9,...,2020-01-03,109.1,131.3,155.5,5.03,10.04,73.2,928.38,94.7,0.68
2020-01-04,2020-01-04 17:00:00,4.4,28.0,146,42,5.5,76,929.2,243.0,0.5,...,2020-01-04,117.3,35.4,121.6,4.79,5.74,70.3,930.70,124.0,0.97
2020-01-05,2020-01-05 17:00:00,7.1,16.0,334,52,7.6,53,924.5,291.0,0.8,...,2020-01-05,34.0,662.3,237.9,7.17,6.89,48.4,926.49,303.1,0.80
2020-01-06,2020-01-06 17:00:00,5.0,22.0,248,51,5.2,66,925.0,208.0,0.9,...,2020-01-06,119.9,82.3,134.4,5.78,5.39,55.3,925.14,208.6,0.81
2020-01-07,2020-01-07 17:00:00,6.2,19.0,315,54,8.6,66,927.5,211.0,1.1,...,2020-01-07,44.7,593.6,235.1,6.84,7.61,54.6,927.93,214.5,0.95
2020-01-08,2020-01-08 17:00:00,7.9,19.0,310,54,16.3,54,924.9,199.0,0.8,...,2020-01-08,39.3,612.4,231.9,8.34,16.45,43.5,926.29,168.4,0.65
2020-01-09,2020-01-09 17:00:00,8.1,30.0,131,47,9.3,75,920.7,292.0,7.5,...,2020-01-09,109.0,230.4,181.2,7.67,11.17,77.3,920.86,219.7,3.07

In [43]:
# list out the column names
new_df.columns

Index(['PeriodEnd', 'Temperature', 'Radiation', 'DNI', 'GHI', 'Precipitation',
       'Humidity', 'Pressure', 'WindDirection', 'WindSpeed', 'MonthPE', 'Date',
       'Daily_radiation', 'Daily_DNI', 'Daily_GHI', 'Daily_Temp',
       'Daily_Precip', 'Daily_Humidity', 'Daily_Pressure', 'Daily_WindDir',
       'Daily_WindSpeed'],
      dtype='object')

In [44]:
# select column features
final_df= new_df[['MonthPE', 'Date','Daily_Temp','Daily_Precip', 'Daily_Humidity', 'Daily_Pressure',\
                  'Daily_WindDir','Daily_WindSpeed','Daily_DNI', 'Daily_GHI','Daily_radiation']]

In [45]:
# print the first 5 rows
final_df.head()

,MonthPE,Date,Daily_Temp,Daily_Precip,Daily_Humidity,Daily_Pressure,Daily_WindDir,Daily_WindSpeed,Daily_DNI,Daily_GHI,Daily_radiation
2019-12-31,12,2019-12-31,7.71,3.88,39.5,928.02,126.4,0.71,631.7,234.8,37.7
2020-01-01,1,2020-01-01,6.05,4.19,57.5,927.81,155.9,0.65,626.8,234.5,40.8
2020-01-02,1,2020-01-02,5.01,6.66,63.7,925.93,133.0,0.89,309.3,191.5,101.5
2020-01-03,1,2020-01-03,5.03,10.04,73.2,928.38,94.7,0.68,131.3,155.5,109.1
2020-01-04,1,2020-01-04,4.79,5.74,70.3,930.70,124.0,0.97,35.4,121.6,117.3

In [46]:
# show the number of rows and column
final_df.shape

(727, 11)

In [47]:
# save cleaned dataset
final_df.to_csv('../dataset/Solcast_leon_20_21_clean.csv')